development:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  # are up to date. `bun install` will do this check automatically, but you can also run
  # `bin/webpacker --check-bun` or `bun check` manually.
  check_bun_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'